name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger workflow on push to main branch

permissions:
  contents: read  # No write permissions required for main branch deployment
  contents: write
  pages: write
  id-token: write  # Required for GitHub Pages deployment via Actions

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Ensure Files are Ready
      - name: Verify Static Files
        run: |
          if [ ! -f index.html ]; then
            echo "index.html not found. Please ensure your site files are in the root directory."
            exit 1
          fi
          echo "Static files verified."

      # Step 3: Deployment Confirmation
      - name: Deployment Confirmation
        run: echo "Your site is deployed and available at https://<your-username>.github.io/<repository-name>/"
      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload Files for Deployment
        uses: actions/upload-pages-artifact@v2
        with:
          path: .  # Deploy everything from the root directory

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
