name: Deploy Terminal Portfolio

on:
  push:
    branches:
      - main  # Trigger the workflow when pushing to the main branch

permissions:
  contents: read  # No write permissions required for main branch deployment

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Ensure Files are Ready
      - name: Verify Static Files
        run: |
          if [ ! -f index.html ]; then
            echo "index.html not found. Please ensure your site files are in the root directory."
            exit 1
          fi
          echo "Static files verified."

      # Step 3: Deployment Confirmation
      - name: Deployment Confirmation
        run: echo "Your site is deployed and available at https://<your-username>.github.io/<repository-name>/"
