name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger workflow on push to main branch

permissions:
  contents: write
  pages: write
  id-token: write  # Required for GitHub Pages deployment via Actions

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v3

      - name: Build Static Site
        run: |
          mkdir -p build
          cp -R * build/  # Copy all project files to the build directory
          rm -rf build/.git  # Exclude the Git directory to avoid conflicts

      - name: Upload Files for Deployment
        uses: actions/upload-pages-artifact@v2
        with:
          path: build  # Deploy everything from the build directory

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
