name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger workflow on push to main branch

permissions:
  contents: write
  pages: write
  id-token: write  # Required for GitHub Pages deployment via Actions

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v3

      - name: Upload Files for Deployment
        uses: actions/upload-pages-artifact@v2
        with:
          path: .  # Deploy everything from the root directory

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
