name: Deploy to GitHub Pages

on:
  push:
    branches:
      - 1-outdated-commands-still-appear-in-help-menu # Trigger workflow on this branch

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload Site Content
        uses: actions/upload-pages-artifact@v2
        with:
          path: .  # Upload all files from the root directory

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2

      - name: Confirm Deployment
        if: success()
        run: echo "✅ Deployment successful! Site deployed from '1-outdated-commands-still-appear-in-help-menu'."
